language: rust

services:
    - docker

before_install:
    - docker pull jean553/docker-kafka
    - docker run -d --name docker-kafka jean553/docker-kafka

rust:
    - nightly

before_script:
    - cd rocket-kafka/ 

script:
    - cargo build --bin rocket-kafka
    - cargo run --bin rocket-kafka & echo $! > /tmp/service.pid 
    - sleep 5 # let some time for the service to start
    - kill "$(cat /tmp/service.pid)"
